version: 0.2

phases:
  install:
    commands:
      - echo "Installing MySQL client and jq"
      - apt-get update -y
      - apt-get install -y mysql-client jq
      - echo "Fetching MySQL credentials from AWS Secrets Manager"
      - MYSQL_SECRET=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:488560023623:secret:MySQL-credentials_v6-orCWPr --query SecretString --output text)
      - export MYSQL_USERNAME=$(echo $MYSQL_SECRET | jq -r .username)
      - export MYSQL_PASSWORD=$(echo $MYSQL_SECRET | jq -r .password)
      - export MYSQL_HOST=$(echo $MYSQL_SECRET | jq -r .host)
      - export MYSQL_PORT=$(echo $MYSQL_SECRET | jq -r .port)
      - export MYSQL_DATABASE=employees  # Manually setting database name

  build:
    commands:
      - echo "Running MySQL query"
      - mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USERNAME -p"$MYSQL_PASSWORD" $MYSQL_DATABASE -e "SELECT * FROM employees LIMIT 10;"

artifacts:
  files:
    - '/*'
