name: CI/CD Pipeline for MySQL Setup on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest  # Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install MySQL client and jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client jq

      - name: Retrieve DB credentials from AWS Secrets Manager
        id: fetch-secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id MySQL-credentials_v7 --query SecretString --output text)
          echo "MYSQL_USER=$(echo $SECRET | jq -r '.username')" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=$(echo $SECRET | jq -r '.password')" >> $GITHUB_ENV
          echo "MYSQL_HOST=$(echo $SECRET | jq -r '.host')" >> $GITHUB_ENV
          echo "MYSQL_PORT=3307" >> $GITHUB_ENV  # Assuming port is 3307

      - name: Make query script executable
        run: chmod +x sql_query.sh

      - name: Execute MySQL query
        run: ./sql_query.sh
        env:
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_PORT: ${{ env.MYSQL_PORT }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASS: ${{ env.MYSQL_PASS }}

      - name: Save query results
        if: always()
        run: |
          ./sql_query.sh > query_results.txt
          echo "QUERY_RESULTS=$(cat query_results.txt)" >> $GITHUB_ENV

      - name: Upload query results as artifact
        uses: actions/upload-artifact@v3.1.0 # Updated to a specific stable version
        with:
          name: mysql-query-results
          path: query_results.txt
