name: CI/CD Pipeline for MySQL Setup on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest  # Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install MySQL client and jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client jq

      - name: Retrieve DB credentials from AWS Secrets Manager
        id: fetch-secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id my-db-secret --query SecretString --output text)
          echo "MYSQL_USER=$(echo $SECRET | jq -r '.username')" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=$(echo $SECRET | jq -r '.password')" >> $GITHUB_ENV
          echo "MYSQL_HOST=$(echo $SECRET | jq -r '.host')" >> $GITHUB_ENV
          echo "MYSQL_PORT=3307" >> $GITHUB_ENV  # Assuming port is 3307

      - name: Test MySQL connection
        run: |
          mysqladmin ping -h "$MYSQL_HOST" --port="$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD"
      
      - name: Run SQL script on MySQL
        run: |
          mysql -h "$MYSQL_HOST" --port="$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" < ./employees.sql
