name: Run Query Script

on:
  push:
    branches:
      - main

jobs:
  run-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve DB secrets
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id MySQL-credentials_v7 --query SecretString --output text)
          echo "DB_HOST=$(echo $SECRET_JSON | jq -r .db_host)" >> $GITHUB_ENV
          echo "DB_USER=$(echo $SECRET_JSON | jq -r .db_user)" >> $GITHUB_ENV
          echo "DB_PASS=$(echo $SECRET_JSON | jq -r .db_pass)" >> $GITHUB_ENV
          echo "DB_NAME=$(echo $SECRET_JSON | jq -r .db_name)" >> $GITHUB_ENV

      - name: Run Script
        run: |
          chmod +x sql_query.sh
          ./sql_query.sh
